### ISSUE TITLE
[watchdog_node] Kill multiple nodes

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_apps#54]
Add an action to kill multiple nodes. Our use case is the openni2 node plus the skeleton tracker which typically both need to be restarted.

**Comment by cburbridge** [comment]
You could use multiple instances of the existing KillNode action within a single watchdog:

```
- name: Camera Node Watchdog
  description: Monitors the camera driver node to ensure still publishing. If not, kills it.
  restart_timeout: 30
  monitors:
      - monitor_type: TopicAlive
        topic: /camera/camera_info
        max_duration: 10
  actions:
      - action_type: KillNode
        node_name: /camera_node
      - action_type: KillNode
        node_name: /skeleton_tracker
```
